### ISSUE TITLE
[Suggestion] Tooltip

### ISSUE THREAD

**Issue by byr0n3** [enumiton/renum#77]
### Suggestion

Preferably using a custom attribute like `data-tooltip="This is a tooltip."`. Shows a small tooltip over the element which shows the text from the attribute.

**Comment by enumiton** [comment]
A tooltip component will definitely be coming. It will likely be in the form a component rather than a attribute due to accessibility and positioning issues.

I'll also add a minimal version using only css and custom attributes, though I won't recommend using it due to the issues mentioned above.

**Comment by enumiton** [comment]
https://github.com/enumiton/renum/releases/tag/v0.6.0

CSS-only variant soon™
